[package]
name = "mire-model"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.15", features = ["serde"] }
uuid = { version = "0.8.1", features = ["v4", "serde"] }