[package]
name = "mire-server"
version = "0.1.0"
authors = ["Graham Cox <graham@grahamcox.co.uk>"]
edition = "2018"

[dependencies]
actix-cors = "0.3.0"
actix-http = "2.0.0"
actix-web = "3.0.1"
bytes = "0.5.6"
serde_json = { version = "1.0.57", features = ["preserve_order"] }
tracing = "0.1.19"
