[workspace]

members = [
    "crates/authentication",
    "crates/authorization",
    "crates/database",
    "crates/health",
    "crates/http",
    "crates/mire",
    "crates/model",
    "crates/server",
    "crates/testdata",
    "crates/testdatabase",
    "crates/users",
    "crates/world"
]
