[workspace]

members = [
    "crates/authentication",
    "crates/authorization",
    "crates/database",
    "crates/health",
    "crates/mire",
    "crates/model",
    "crates/server",
    "crates/testdatabase",
    "crates/users"
]
