version: "3"

services:
  mire-dev-postgres:
    image: postgres:11.6-alpine
    environment:
      POSTGRES_DB: mire
      POSTGRES_USER: mire
      POSTGRES_PASSWORD: mire
    ports:
      - "127.0.0.1:45432:5432"
    networks:
      - mire-dev

  mire-dev-phppgadmin:
    image: dockage/phppgadmin:latest
    environment:
      - PHP_PG_ADMIN_SERVER_DESC=mire
      - PHP_PG_ADMIN_SERVER_HOST=mire-dev-postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_SSL_MODE=disable
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=mire
      - PHP_PG_ADMIN_SHOW_ADVANCED=true
      - PHP_PG_ADMIN_SHOW_COMMENTS=true
      - PHP_PG_ADMIN_OWNED_ONLY=true
      - PHP_PG_ADMIN_SHOW_SYSTEM=true
      - PHP_PG_ADMIN_SHOW_OIDS=true
    ports:
      - "127.0.0.1:48081:80"
    depends_on:
      - mire-dev-postgres
    networks:
      - mire-dev

networks:
  mire-dev:
