name: CI

on: [push]

jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14"

      - run: go version

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.28
          working-directory: service

      - name: Tests
        working-directory: service
        run: |
          go test ./internal/...
          go test ./integration/...
